const SELECTORS = {
    HEADER_LEFT: ".oxy-header-left",
    OXY_MEGA_DROPDOWN_LINK_TEXT: ".oxy-mega-dropdown_link-text",
    COOKIE_ACCEPT_BUTTON: "._brlbs-accept",
    HEADER_CENTER: ".oxy-header-center",
    SEARCH_ICON: ".oxy-header-search_open-icon",
    SEARCH_FIELD: ".oxy-header-search_search-field",
    HEADLINE: "[class='ct-headline ']",
    H1: "h1",
    H2: "h2",
    CODE_BLOCK: "[class='ct-code-block ']",
    CT_LINK: ".ct-link",
    MEMU_ITEM_AREA: ".menu-item-area",
    CT_DIV_BLOCK: ".ct-div-block",
    HAS_BOX_SHADOW: ".has-box-shadow",
    HS_FORM_PRIVATE: ".hs-form-private",
    FIRST_NAME: "[name='firstname']",
    LAST_NAME: "[name='lastname']",
    EMAIL: "[name='email']",
    MOBILE_PHONE: "[name='mobilephone']",
    COMPANY: "[name='company']",
    COUNTRY: "[name='country']",
    HOW_HEAR: "[name='how_did_you_hear_about_mostly_ai___free_text']",
    MESSAGE: "[name='message']",
    HS_FORM_CHECKBOX: ".hs-form-booleancheckbox",
    BTN_BLOCK: ".btn-block",
    SUBMITTED_MESSAGE: ".submitted-message",
};
export default SELECTORS;
